app/blueprints/posts.py
from sqlite3.dbapi2 import Row

from flask import Blueprint, flash, g, redirect, render_template, request, url_for
from werkzeug.exceptions import abort
from werkzeug.wrappers.response import Response

from app.db import get_db
from app.fixtures import login_required

bp = Blueprint("posts", __name__, url_prefix="/posts")


@bp.route("/create", methods=("GET", "POST"))
@login_required
def create() -> Response | str:
    """Allow authenticated users to create new posts."""
    if request.method == "POST":
        title = request.form["title"]
        body = request.form["body"]
        error = None

        if not title:
            error = "Title is required."

        if error is not None:
            flash(error)
        else:
            db = get_db()
            db.execute(
                "insert into posts (title, body, author_id) values (?, ?, ?)",
                (title, body, g.user["id"]),
            )
            db.commit()

            return redirect(url_for("root.index"))

    return render_template("posts/create.html")


def get_post(post_id: int, check_author: bool = True) -> Row:
    """Get data for a specified post."""
    post = (
        get_db()
        .execute(
            """
        select p.id
             , p.title
             , p.body
             , p.created
             , p.author_id
             , u.username
          from posts p
               join users u
                 on u.id = p.author_id
         where p.id = ?
        """,
            (post_id,),
        )
        .fetchone()
    )

    if post is None:
        abort(404, f"Post id {post_id} doesn't exist.")

    if check_author and post["author_id"] != g.user["id"]:
        abort(403)

    return post


@bp.route("/<int:post_id>/update", methods=("GET", "POST"))
@login_required
def update(post_id: int) -> Response | str:
    """Allow authenticated users to update an existing post."""
    post = get_post(post_id)

    if request.method == "POST":
        title = request.form["title"]
        body = request.form["body"]
        error = None

        if not title:
            error = "Title is required."

        if error is not None:
            flash(error)
        else:
            db = get_db()
            db.execute(
                """
                update posts
                   set title = ?
                     , body = ?
                 where id = ?
                 """,
                (title, body, post_id),
            )
            db.commit()
            return redirect(url_for("root.index"))

    return render_template("posts/update.html", post=post)


@bp.route("/<int:post_id>/delete", methods=("POST",))
@login_required
def delete(post_id: int) -> Response:
    """Allow authenticated users to delete a post"""
    get_post(post_id)
    db = get_db()
    db.execute("delete from posts where id = ?", (post_id,))
    db.commit()
    return redirect(url_for("root.index"))

app/templates/posts/create.html
{% extends 'base.html' %}

{% block title %}New Post{% endblock %}

{% block content %}

  <form method="post">
    <div class="field">
      <label class="label" for="title">Title</label>
      <div class="control">
        <input class="input" type="text" name="title" id="title" value="{{ request.form['title'] }}" required>
      </div>
    </div>
    <div class="field">
      <label class="label" for="body">Body</label>
      <div class="control">
        <textarea class="textarea" name="body" id="body">{{ request.form['body'] }}</textarea>
      </div>
    </div>
    <div class="field">
      <p class="control">
        <input class="button is-success" type="submit" value="Save">
      </p>
    </div>
  </form>

{% endblock %}

app/templates/posts/index.html
{% extends 'base.html' %}

{% block title %}Posts{% endblock %}

{% block content %}

  {% for post in posts %}

    <div class="card">
      <div class="card-content">
        <p class="title has-text-centered">{{ post['title'] }}</p>
        <p class="subtitle has-text-centered">by {{ post['username'] }} on {{ post['created'].strftime('%Y-%m-%d') }}</p>
        <hr>
        <div class="content">{{ post['body'] }}</div>
      </div>
      {% if g.user['id'] == post['author_id'] %}
        <footer class="card-footer">
          <a class="card-footer-item" href="{{ url_for('posts.update', post_id=post['id']) }}">Edit</a>
        </footer>
      {% endif %}
    </div>

    {% if not loop.last %}
      <hr>
    {% endif %}

  {% endfor %}
{% endblock %}

app/templates/posts/update.html
{% extends 'base.html' %}

{% block title %}{{ request.form['title'] or post['title'] }}{% endblock %}

{% block content %}

  <form method="post">
    <div class="field">
      <label class="label" for="title">Title</label>
      <div class="control">
        <input class="input" type="text" name="title" id="title" value="{{ request.form['title'] or post['title'] }}" required>
      </div>
    </div>
    <div class="field">
      <label class="label" for="body">Body</label>
      <div class="control">
        <textarea class="textarea" name="body" id="body">{{ request.form['body'] or post['body'] }}</textarea>
      </div>
    </div>
    <div class="field">
      <p class="control">
        <input class="button is-success" type="submit" value="Save">
      </p>
    </div>
  </form>
  <hr>
  <form action="{{ url_for('posts.delete', post_id=post['id']) }}" method="post">
    <p class="control">
      <input class="button is-danger" type="submit" value="Delete" onclick="return confirm('Are you sure?');">
    </p>
  </form>

{% endblock %}