app/auth.py
import functools
from typing import Any, Callable

from flask import (
    Blueprint,
    flash,
    g,
    redirect,
    render_template,
    request,
    session,
    url_for,
)
from werkzeug.security import check_password_hash, generate_password_hash
from werkzeug.wrappers.response import Response

from app.db import get_db

bp = Blueprint("auth", __name__, url_prefix="/auth")


@bp.route("/register", methods=("GET", "POST"))
def register() -> Response | str:
    """Register a new user."""
    if request.method == "POST":
        username = request.form["username"]
        password = request.form["password"]
        db = get_db()
        error = None

        if not username:
            error = "Username is required."
        elif not password:
            error = "Password is required."

        if error is None:
            try:
                db.execute(
                    "insert into users (username, password) values (?, ?)",
                    (username, generate_password_hash(password)),
                )
                db.commit()

            except db.IntegrityError:
                error = f"User {username} is already registered."

            else:
                return redirect(url_for("auth.login"))

        flash(error)

    return render_template("auth/register.html")


@bp.route("/login", methods=("GET", "POST"))
def login() -> Response | str:
    """Authenticate an existing user."""
    if request.method == "POST":
        username = request.form["username"]
        password = request.form["password"]
        db = get_db()
        error = None
        user = db.execute(
            "select * from users where username = ?", (username,)
        ).fetchone()

        if user is None:
            error = "Incorrect username."
        elif not check_password_hash(user["password"], password):
            error = "Incorrect password."

        if error is None:
            session.clear()
            session["user_id"] = user["id"]
            return redirect(url_for("index"))

        flash(error)

    return render_template("auth/login.html")


@bp.before_app_request
def load_logged_in_user() -> None:
    """Get the ID of the currently authenticated user."""
    user_id = session.get("user_id")

    if user_id is None:
        g.user = None
    else:
        g.user = (
            get_db().execute("select * from users where id = ?", (user_id,)).fetchone()
        )


@bp.route("/logout")
def logout() -> Response:
    """Log the user out for the current session."""
    session.clear()
    return redirect(url_for("index"))


def login_required(view) -> Callable[[dict[str, Any]], Response | Any]:
    """A decorator to use for requiring that a user be authenticated when submitting a request."""

    @functools.wraps(view)
    def wrapped_view(**kwargs) -> Response | Any:
        if g.user is None:
            return redirect(url_for("auth.login"))

        return view(**kwargs)

    return wrapped_view

app/blueprints/posts.py
from sqlite3.dbapi2 import Row

from flask import Blueprint, flash, g, redirect, render_template, request, url_for
from werkzeug.exceptions import abort
from werkzeug.wrappers.response import Response

from app.db import get_db
from app.fixtures import login_required

bp = Blueprint("posts", __name__, url_prefix="/posts")


@bp.route("/create", methods=("GET", "POST"))
@login_required
def create() -> Response | str:
    """Allow authenticated users to create new posts."""
    if request.method == "POST":
        title = request.form["title"]
        body = request.form["body"]
        error = None

        if not title:
            error = "Title is required."

        if error is not None:
            flash(error)
        else:
            db = get_db()
            db.execute(
                "insert into posts (title, body, author_id) values (?, ?, ?)",
                (title, body, g.user["id"]),
            )
            db.commit()

            return redirect(url_for("root.index"))

    return render_template("posts/create.html")


def get_post(post_id: int, check_author: bool = True) -> Row:
    """Get data for a specified post."""
    post = (
        get_db()
        .execute(
            """
        select p.id
             , p.title
             , p.body
             , p.created
             , p.author_id
             , u.username
          from posts p
               join users u
                 on u.id = p.author_id
         where p.id = ?
        """,
            (post_id,),
        )
        .fetchone()
    )

    if post is None:
        abort(404, f"Post id {post_id} doesn't exist.")

    if check_author and post["author_id"] != g.user["id"]:
        abort(403)

    return post


@bp.route("/<int:post_id>/update", methods=("GET", "POST"))
@login_required
def update(post_id: int) -> Response | str:
    """Allow authenticated users to update an existing post."""
    post = get_post(post_id)

    if request.method == "POST":
        title = request.form["title"]
        body = request.form["body"]
        error = None

        if not title:
            error = "Title is required."

        if error is not None:
            flash(error)
        else:
            db = get_db()
            db.execute(
                """
                update posts
                   set title = ?
                     , body = ?
                 where id = ?
                 """,
                (title, body, post_id),
            )
            db.commit()
            return redirect(url_for("root.index"))

    return render_template("posts/update.html", post=post)


@bp.route("/<int:post_id>/delete", methods=("POST",))
@login_required
def delete(post_id: int) -> Response:
    """Allow authenticated users to delete a post"""
    get_post(post_id)
    db = get_db()
    db.execute("delete from posts where id = ?", (post_id,))
    db.commit()
    return redirect(url_for("root.index"))

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>{% block title %}{% endblock %} - Heavy Metal Machine</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
    <script src="{{ url_for('static', filename='script.js') }}" defer></script>
    <script src="https://kit.fontawesome.com/abcb054d0c.js" crossorigin="anonymous" defer></script>
  </head>
  <body>
    <nav class="navbar is-light" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
        <a class="navbar-item" href="/">
          Heavy Metal Machine
        </a>
        <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="heavyMetalNavbar">
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
        </a>
      </div>
      <div id="heavyMetalNavbar" class="navbar-menu">
        <div class="navbar-start">
          <a class="navbar-item" href="/">
            Home
          </a>
        </div>
        <div class="navbar-end">
          <div class="navbar-item">
            <div class="buttons">
              {% if g.user %}
                <a class="button is-success" href="{{ url_for('posts.create') }}">
                  <span class="icon-text">
                    <span class="icon">
                      <i class="fa-solid fa-plus"></i>
                    </span>
                    <span>Create Post</span>
                  </span>
                </a>
                <a class="button is-danger" href="{{ url_for('auth.logout') }}">
                  Log Out
                </a>
              {% else %}
                <a class="button is-primary" href="{{ url_for('auth.register') }}">
                  Sign Up
                </a>
                <a class="button is-light" href="{{ url_for('auth.login') }}">
                  Log In
                </a>
              {% endif %}
            </div>
          </div>
        </div>
      </div>
    </nav>
    <main>
      <section class="section">
        <div class="container">
          <div class="columns">
            <div class="column is-three-fifths is-offset-one-fifth">
              {% for message in get_flashed_messages() %}
                <div class="notification is-danger">
                  <button class="delete"></button>
                    {{ message }}
                </div>
              {% endfor %}
              {% block content %}{% endblock %}
            </div>
          </div>
        </div>
      </section>
    </main>
  </body>
</html>